### ISSUE TITLE
Why xlAnyKey?

### ISSUE THREAD

**Issue by Greedquest** [cristianbuse/VBA-FastExcelUDFs#2]
Could you not allow the default Esc Key - i.e. just make sure it's not xlNoKey?

> ## Notes
> * The Fast Calculation is only triggered if a Calculation Interruption is possible. For that make sure:  
> ```diff
> - Application.CalculationInterruptKey = xlAnyKey
> + Application.CalculationInterruptKey <> xlNoKey
> ```

**Comment by cristianbuse** [comment]
Hi @Greedquest ,

If ```Application.CalculationInterruptKey``` is set to ```xlEscKey``` then the 'fake' mouse input being sent in the ```InterruptCalculation``` method does not stop the calculation.

I tried sending an Esc key input a few years ago but never got it to work properly and so I went with the mouse input. I should probably try again as I posses more knowledge now than back then but for now your suggestion does not work with the current 
 mouse approach.

Thanks!
